## Quantum Computation from Scratch

In [2]:
import numpy as np
import math

In [3]:
zero_ket=np.array([[1],[0]])
one_ket=np.array([[0],[1]])

In [4]:
zero_ket

array([[1],
       [0]])

In [5]:
one_ket

array([[0],
       [1]])

In [6]:
c1=1/2**0.5
c2=1/2**0.5

In [7]:
psi=c1*zero_ket+c2*one_ket

In [8]:
psi

array([[0.70710678],
       [0.70710678]])

In [9]:
gate_H = 1.0 / 2**0.5 * np.array([[1, 1],
                             [1, -1]])

In [10]:
psi_new=np.dot(gate_H,psi)

In [11]:
psi_new

array([[1.],
       [0.]])

In [12]:
phi=math.pi

In [13]:
gate_phi = np.array([[1, 0], [0, math.e**(1j*phi)]])

In [14]:
gate_phi

array([[ 1.+0.0000000e+00j,  0.+0.0000000e+00j],
       [ 0.+0.0000000e+00j, -1.+1.2246468e-16j]])

In [15]:
chi=np.dot(gate_H,(np.dot(gate_phi,np.dot(gate_H,psi))))

In [16]:
chi

array([[0.70710678+0.j],
       [0.70710678+0.j]])

In [17]:
chi2=np.dot(gate_H,(np.dot(gate_phi,np.dot(gate_H,psi))))

In [18]:
chi2

array([[0.70710678+0.j],
       [0.70710678+0.j]])

## Quantum Not Gate

In [19]:
gate_X=np.dot(gate_H,(np.dot(gate_phi,np.dot(gate_H,zero_ket))))

In [20]:
gate_X_matrix=np.array([[0,1],[1,0]])

In [21]:
gate_X_matrix

array([[0, 1],
       [1, 0]])

In [22]:
out=np.dot(gate_X_matrix,np.array([[1],[0]]))

In [23]:
out

array([[0],
       [1]])

In [24]:
psi

array([[0.70710678],
       [0.70710678]])

In [25]:
psi_not=np.dot(gate_X_matrix,psi)

In [26]:
psi_not

array([[0.70710678],
       [0.70710678]])

## 2 Qubit Quantum System

In [27]:
zero_ket=np.array([[1],[0]])
one_ket=np.array([[0],[1]])

In [28]:
zero_zero=np.kron(zero_ket,zero_ket)

In [29]:
zero_zero

array([[1],
       [0],
       [0],
       [0]])

In [30]:
zero_one=np.kron(zero_ket,one_ket)

In [31]:
one_zero=np.kron(one_ket,zero_ket)

In [32]:
one_one=np.kron(one_ket,one_ket)

In [33]:
one_one

array([[0],
       [0],
       [0],
       [1]])

In [39]:
c00 = c01 = c10 = c11 = 1/4

In [40]:
psi=c00*zero_zero+c01*zero_one+c10*one_zero+c11*one_one

In [41]:
psi

array([[0.25],
       [0.25],
       [0.25],
       [0.25]])